language: python

python:
  - "2.6"
  - "pypy"
  

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
  - REQUIREMENTS=devel

install:
  - pip install -r .travis-$REQUIREMENTS-requirements.txt
  - pip install --editable .

script: make test

