language: python
build_environment: ubuntu1304
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
  - REQUIREMENTS=devel

matrix:
  exclude:
    # Python 3 support currently does not work with lowest requirements
    - python: "3.3"
      env: REQUIREMENTS=lowest

install:
  - pip install -r .travis-$REQUIREMENTS-requirements.txt
  - pip install --editable .

script: make test

